version: '3.8'

services:
  # FastAPI application container
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"  # Expose FastAPI app on port 8000
    depends_on:
      - db  # Ensures FastAPI starts after the database

  # PostgreSQL database container
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist database data
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432

volumes:
  db_data:
    driver: local
